version: 2.1

orbs:
  heroku: circleci/heroku@1.0.1

workflows:
  sample:
    jobs:
      - build-and-test


jobs:
  deploy:
    executor: heroku/default
    steps:
      - checkout
      - run:
          name: Storing previous commit
          command: |
            git rev-parse HEAD > ./commit.txt
      - heroku/install
      - setup_remote_docker:
          version: 18.06.0-ce
      - run:
          name: Pushing to heroku registry
          command: |
            heroku container:login
            heroku container:push web -a=rocky-citadel-41338
            heroku container:release web -a rocky-citadel-41338

